export const GET_LOGGED_PROFILE = "GET_LOGGED_PROFILE";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";
export const GET_PROFILE_VOTES = "GET_PROFILE_VOTES";
export const GET_TRENDING_POSTS = "GET_TRENDING_POSTS";
export const POST_FOLLOWING_TO_STATE = "POST_FOLLOWING_TO_STATE";
export const POST_VOTES_TO_STATE = "POST_FOLLOWING_TO_STATE";
