//Function to decide which html tag can be rendered in post
const postAllowedHtml = props => {
  if (props === "photos" || props === "gifs") {
    return [
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "blockquote",
      "p",
      "a",
      "ul",
      "ol",
      "nl",
      "li",
      "b",
      "i",
      "strong",
      "em",
      "strike",
      "code",
      "hr",
      "br",
      "div",
      "table",
      "thead",
      "caption",
      "tbody",
      "tr",
      "th",
      "td",
      "pre"
    ];
  } else {
    return [
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "blockquote",
      "img",
      "p",
      "a",
      "ul",
      "ol",
      "nl",
      "li",
      "b",
      "i",
      "strong",
      "em",
      "strike",
      "code",
      "hr",
      "br",
      "div",
      "table",
      "thead",
      "caption",
      "tbody",
      "tr",
      "th",
      "td",
      "pre"
    ];
  }
};
export default postAllowedHtml;
